### ISSUE TITLE
Error while parsing event data [2019 UDP format]

### ISSUE THREAD

**Issue by Dnalop** [jonybur/f1-telemetry-client#14] opened 2019-07-11 14:02 UTC
Hello. I was testing my application, and driving around a circuit (it was Albert Park, Australia). When I entered new lap, telemetry client crashed. I don't think it's a bug in my application, the error output only points at parser itself. I use the latest UDP format, which is sent with 10 Hz frequency. Also, here's the error report I got:

```
PATH_TO_MY_APP\node_modules\f1-telemetry-client\build\src\parsers\packets\PacketEventDataParser.js:13
                this.uint8('vehicleIdx').float('lapTime');
                                         ^

TypeError: this.uint8(...).float is not a function
    at PacketEventDataParser.unpack2019Format (PATH_TO_MY_APP\node_modules\f1-telemetry-client\build\src\parsers\packets\PacketEventDataParser.js:13:42)
    at new PacketEventDataParser (PATH_TO_MY_APP\node_modules\f1-telemetry-client\build\src\parsers\packets\PacketEventDataParser.js:34:18)
    at F1TelemetryClient.parseMessage (PATH_TO_MY_APP\node_modules\f1-telemetry-client\build\src\index.js:74:28)
    at Socket.<anonymous> (PATH_TO_MY_APP\node_modules\f1-telemetry-client\build\src\index.js:93:45)
    at Socket.emit (events.js:196:13)
    at UDP.onMessage [as onmessage] (dgram.js:849:8)
```

Feel free to ask about more details, if you need.
Cheers.

Edit 1:

@jonybur, I've noticed, that this error occurrs after finishing 1st lap of the session (time trial, to be precise). 

Edit 2:

The error actually occurrs every time you finish a lap.

**Comment by jonybur** [comment] 2019-07-11 16:20
Thank you for the heads up. I will try to reproduce ASAP to come up with a fix for this.

**Comment by Dnalop** [comment] 2019-07-11 16:47
> Thank you for the heads up. I will try to reproduce ASAP to come up with a fix for this.

No problem. Glad that I can help

**Comment by jonybur** [comment] 2019-07-13 19:38
Hi @Dnalop,

I've been testing the client with the following game settings:
> UDP Broadcast Mode: On
> UDP Port: 20777
> UDP Send Rate: 10Hz
> UDP Format: 2019

From what Im seeing, you're getting a crash when the game sends a FastestLap event code, since that's the only time the parser has to unpack the buffer using `this.uint8('vehicleIdx').float('lapTime')`

I have tried getting FastestLaps events (event code FTLP), and I still could not get the crash that you're getting.

It would be very valuable if you could please try to reproduce the bug once more but running the telemetry client in the branch "bug/ftlp-crash" that I just created.

Running on this branch, every time the FastestLap event triggers you will get a console log that reads something like `Buffer:  {"type":"Buffer","data":[227,7,1,4,1,3,8,34,107,18,10,175,41,8,226,189,114,67,219,10,0,0,0,70,84,76,80,0,40,177,109,66]}`

With that buffer dump I will be able to deduce why the parser is failing.

Thank you

**Comment by Dnalop** [comment] 2019-07-14 10:49
> Hi @Dnalop,
> 
> I've been testing the client with the following game settings:
> 
> > UDP Broadcast Mode: On
> > UDP Port: 20777
> > UDP Send Rate: 10Hz
> > UDP Format: 2019
> 
> From what Im seeing, you're getting a crash when the game sends a FastestLap event code, since that's the only time the parser has to unpack the buffer using `this.uint8('vehicleIdx').float('lapTime')`
> 
> I have tried getting FastestLaps events (event code FTLP), and I still could not get the crash that you're getting.
> 
> It would be very valuable if you could please try to reproduce the bug once more but running the telemetry client in the branch "bug/ftlp-crash" that I just created.
> 
> Running on this branch, every time the FastestLap event triggers you will get a console log that reads something like `Buffer: {"type":"Buffer","data":[227,7,1,4,1,3,8,34,107,18,10,175,41,8,226,189,114,67,219,10,0,0,0,70,84,76,80,0,40,177,109,66]}`
> 
> With that buffer dump I will be able to deduce why the parser is failing.
> 
> Thank you

Alright, I'll try to reproduce the bug, and see what happens. And btw. when the lap wasn't fastest, the error never occurred.

**Comment by jonybur** [comment] 2019-07-14 20:21
Hi @Dnalop ,

I've been working on this issue and I was (finally) able to reproduce it. Apparently the transpiled version of the cleint throws this error when trying to unpack `float('lapTime')` from the FTLP package. In other words, the only way to reproduce this error is when using this library in another application. For now, in order to avoid getting the crash, you can just take out the `.float('lapTime')` from the `unpack2019Format` method. I will keep trying to fix this and I will update the library ASAP when I am able to find a solution to this problem.

Thank you

**Comment by jonybur** [comment] 2019-07-15 01:24
@Dnalop,

I was finally able to fix this pesky bug, and it is no longer present in `v0.1.11`, which is being merged right now.

Thank you!

**Closed by jonybur** 2019-07-15 01:24 UTC
Labels: bug

**Comment by Dnalop** [comment] 2019-07-15 06:26
> Hi @Dnalop ,
> 
> I've been working on this issue and I was (finally) able to reproduce it. Apparently the transpiled version of the cleint throws this error when trying to unpack `float('lapTime')` from the FTLP package. In other words, the only way to reproduce this error is when using this library in another application. For now, in order to avoid getting the crash, you can just take out the `.float('lapTime')` from the `unpack2019Format` method. I will keep trying to fix this and I will update the library ASAP when I am able to find a solution to this problem.
> 
> Thank you

Alright. I actually stumbled across this error while using my own app, not the playground itself. I actually never use neither event data nor lap time. I'm also comfortable using last year's format (it should still work, shouldn't it). I'll see, if the same error occurrs while using it.

**Comment by Dnalop** [comment] 2019-07-15 06:51
> @Dnalop,
> 
> I was finally able to fix this pesky bug, and it is no longer present in `v0.1.11`, which is being merged right now.
> 
> Thank you!

No problem, glad that I could help 😄
